/**
 * ADAPTERS LAYER — Spanish keyword heuristic for order-status intent.
 *
 * Fires when the customer asks about a previous order: "¿dónde está mi
 * pedido?", "estado de mi compra", "tracking", "ya despacharon", etc.
 *
 * Tunable in `.env`:
 *   ORDER_STATUS_INTENT_PHRASES — comma-separated phrase override. If set,
 *     replaces the built-in Spanish defaults entirely. Useful if Marcos wants
 *     to add region-specific slang or narrow the rule without a code change.
 *
 * If the message contains an explicit order number in `ORD-YYYY-NNNN` format,
 * we surface it so the reply service can prefer it over "latest order".
 */

import { Injectable } from '@nestjs/common';
import {
  IOrderStatusIntent,
  OrderStatusIntentResult,
} from '../../use-cases/conversations/order-status-intent.interface';

const DEFAULT_PHRASES = [
  // Direct status / tracking
  'estado de mi pedido',
  'estado del pedido',
  'estado de mi compra',
  'estado de mi orden',
  'mi pedido',
  'mi compra',
  'mi orden',
  'donde esta mi pedido',
  'donde está mi pedido',
  'donde esta mi compra',
  'donde está mi compra',
  'donde esta mi orden',
  'donde está mi orden',
  'cuando llega',
  'cuándo llega',
  'cuando me llega',
  'cuándo me llega',
  'fecha de entrega',
  'fecha de envio',
  'fecha de envío',
  'seguimiento',
  'tracking',
  'numero de seguimiento',
  'número de seguimiento',
  'rastreo',
  'rastrear',
  'ya despacharon',
  'ya enviaron',
  'ya salio',
  'ya salió',
  'ya entregaron',
  // Bare "envío" / "envio" / "despacho" used to be in this list but they
  // false-positive on pre-sale logistics questions like "hacés envíos al
  // interior?" or "tenés despacho" — Marcos hit this on 2026-05-14 in
  // the ML sandbox. Phrases with possessive or temporal context
  // ("fecha de envío", "ya despacharon", "mi envío" etc.) stay above.
  'mi envio',
  'mi envío',
  'mi despacho',
];

function loadPhrases(): string[] {
  const raw = process.env.ORDER_STATUS_INTENT_PHRASES;
  if (raw && raw.trim().length > 0) {
    return raw
      .split(',')
      .map((s) => s.trim().toLowerCase())
      .filter((s) => s.length > 0);
  }
  return DEFAULT_PHRASES.map((p) => p.toLowerCase());
}

// e.g. "ORD-2026-1234" — the format generated by OrderManagementService
const ORDER_NUMBER_RE = /\b(ORD-\d{4}-\d{4})\b/i;

@Injectable()
export class KeywordOrderStatusIntent implements IOrderStatusIntent {
  private readonly phrases = loadPhrases();

  detect(text: string): OrderStatusIntentResult {
    if (!text || typeof text !== 'string') {
      return { match: false, orderNumber: null, signals: [] };
    }
    const normalized = text.toLowerCase();
    const signals: string[] = [];

    for (const phrase of this.phrases) {
      if (normalized.includes(phrase)) {
        signals.push(`phrase:${phrase}`);
      }
    }

    const numMatch = text.match(ORDER_NUMBER_RE);
    const orderNumber = numMatch ? numMatch[1].toUpperCase() : null;
    if (orderNumber) signals.push(`orderNumber:${orderNumber}`);

    // An explicit order number alone counts as intent — customers often paste
    // their tracking code without surrounding text.
    const match = signals.length > 0;

    return { match, orderNumber, signals };
  }
}
